package com.focustrack.offline;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import org.json.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
    final int BG=Color.rgb(7,21,43), CARD=Color.rgb(12,34,63), GREEN=Color.rgb(53,208,127), TEXT=Color.rgb(239,247,255), MUTED=Color.rgb(157,181,207);
    LinearLayout root, sessionsBox, skillsBox; TextView timer, current, todayTotal, streak; Spinner skillSpinner; EditText topicInput; SeekBar goalBar; TextView goalLabel; Button startBtn, finishBtn;
    SharedPreferences sp; Handler handler=new Handler(); long elapsed=0, startedAt=0; boolean running=false; String selectedSkill="Python"; ArrayList<String> skills=new ArrayList<>();
    Runnable tick=()->{ if(running){ elapsed=(System.currentTimeMillis()-startedAt)/1000; renderTimer(); handler.postDelayed(tick,1000);} };

    @Override public void onCreate(Bundle b){super.onCreate(b); sp=getSharedPreferences("data",0); loadSkills(); buildUI(); refresh();}
    void loadSkills(){String s=sp.getString("skills",""); if(s.isEmpty()){Collections.addAll(skills,"Python","FastAPI","Django","Machine Learning","Deep Learning","Mathematics","Physics","Chemistry","Excel","Power BI","Tableau","SQL"); saveSkills();} else try{JSONArray a=new JSONArray(s);for(int i=0;i<a.length();i++)skills.add(a.getString(i));}catch(Exception e){} }
    void saveSkills(){try{JSONArray a=new JSONArray();for(String s:skills)a.put(s);sp.edit().putString("skills",a.toString()).apply();}catch(Exception e){}}
    TextView tv(String t,int size,int color){TextView v=new TextView(this);v.setText(t);v.setTextSize(size);v.setTextColor(color);v.setPadding(0,4,0,4);return v;}
    GradientDrawable bg(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(r);return g;}
    LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(18,16,18,16);l.setBackground(bg(CARD,24));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,14);l.setLayoutParams(p);return l;}
    Button btn(String t){Button b=new Button(this);b.setText(t);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setTextSize(15);b.setBackground(bg(GREEN,40));b.setPadding(18,8,18,8);return b;}
    @SuppressWarnings("unchecked") void buildUI(){
        ScrollView sv=new ScrollView(this); root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(18,18,18,30);root.setBackgroundColor(BG);sv.addView(root);setContentView(sv);
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL); TextView title=tv("FocusTrack",28,TEXT);title.setTypeface(null,1);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView off=tv("● OFFLINE",12,GREEN);head.addView(off);root.addView(head);
        root.addView(tv("Your private study tracker — no internet required.",14,MUTED));
        LinearLayout c=card();c.addView(tv("TODAY",12,GREEN));todayTotal=tv("0m focused",30,TEXT);todayTotal.setTypeface(null,1);c.addView(todayTotal);streak=tv("🔥 0 day streak",14,MUTED);c.addView(streak);root.addView(c);
        LinearLayout timerCard=card();timerCard.addView(tv("STUDY TIMER",12,GREEN));timer=tv("00:00:00",42,TEXT);timer.setGravity(Gravity.CENTER);timer.setTypeface(null,1);timerCard.addView(timer);
        current=tv("Choose a skill and start.",14,MUTED);current.setGravity(Gravity.CENTER);timerCard.addView(current);
        LinearLayout row=new LinearLayout(this);skillSpinner=new Spinner(this);ArrayAdapter<String> ad=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,skills);skillSpinner.setAdapter(ad);row.addView(skillSpinner,new LinearLayout.LayoutParams(0,55,1));
        topicInput=new EditText(this);topicInput.setHint("Topic (optional)");topicInput.setHintTextColor(MUTED);topicInput.setTextColor(TEXT);topicInput.setSingleLine(true);topicInput.setPadding(14,0,14,0);topicInput.setBackground(bg(Color.rgb(20,48,82),18));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,55,1);tp.setMargins(10,0,0,0);row.addView(topicInput,tp);timerCard.addView(row);
        LinearLayout br=new LinearLayout(this);startBtn=btn("Start");finishBtn=btn("Finish");finishBtn.setEnabled(false);finishBtn.setAlpha(.5f);br.addView(startBtn,new LinearLayout.LayoutParams(0,58,1));LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(0,58,1);fp.setMargins(10,0,0,0);br.addView(finishBtn,fp);timerCard.addView(br);root.addView(timerCard);
        startBtn.setOnClickListener(v->toggle());finishBtn.setOnClickListener(v->finishSession());skillSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int pos,long id){selectedSkill=skills.get(pos);if(!running)current.setText(selectedSkill+" • ready");}});
        LinearLayout goal=card();goal.addView(tv("DAILY GOAL",12,GREEN));goalLabel=tv("1.0 hour",20,TEXT);goal.addView(goalLabel);goalBar=new SeekBar(this);goalBar.setMax(480);goalBar.setProgress((int)(getGoal(selectedSkill)*60));goal.addView(goalBar);goalBar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean f){double h=Math.max(.25,p/60.0);goalLabel.setText(String.format(Locale.US,"%.2f hours",h));}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){sp.edit().putFloat("goal_"+selectedSkill,(float)Math.max(.25,s.getProgress()/60.0)).apply();refresh();}});root.addView(goal);
        TextView sh=tv("SKILL PROGRESS",18,TEXT);sh.setTypeface(null,1);root.addView(sh);skillsBox=new LinearLayout(this);skillsBox.setOrientation(LinearLayout.VERTICAL);root.addView(skillsBox);
        Button add=btn("＋ Add a skill");add.setOnClickListener(v->addSkill());root.addView(add);
        TextView rh=tv("RECENT SESSIONS",18,TEXT);rh.setTypeface(null,1);root.addView(rh);sessionsBox=new LinearLayout(this);sessionsBox.setOrientation(LinearLayout.VERTICAL);root.addView(sessionsBox);
        TextView note=tv("All data stays on this phone. Turn off Wi‑Fi/mobile data and keep studying.",12,MUTED);note.setPadding(4,18,4,0);root.addView(note);
    }
    double getGoal(String s){return sp.getFloat("goal_"+s,1f);}
    long todaySeconds(){String day=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());long total=0;try{JSONArray a=new JSONArray(sp.getString("sessions","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);if(day.equals(o.optString("date")))total+=o.optLong("seconds");}}catch(Exception e){}return total;}
    void refresh(){long sec=todaySeconds();todayTotal.setText(format(sec)+" focused");int days=sp.getInt("streak",0);streak.setText("🔥 "+days+" day streak");renderSkills();renderSessions();}
    void renderTimer(){timer.setText(format(elapsed));}
    String format(long s){return String.format(Locale.US,"%02d:%02d:%02d",s/3600,(s%3600)/60,s%60);}
    void toggle(){if(!running){selectedSkill=skillSpinner.getSelectedItem().toString();running=true;startedAt=System.currentTimeMillis()-elapsed*1000;startBtn.setText("Pause");finishBtn.setEnabled(true);finishBtn.setAlpha(1f);skillSpinner.setEnabled(false);topicInput.setEnabled(false);current.setText(selectedSkill+" • "+(topicInput.getText().toString().trim().isEmpty()?"General":topicInput.getText().toString().trim()));handler.post(tick);}else{running=false;startBtn.setText("Resume");}}
    void finishSession(){if(elapsed<5){Toast.makeText(this,"Study a little longer before saving.",Toast.LENGTH_SHORT).show();return;}running=false;String topic=topicInput.getText().toString().trim();if(topic.isEmpty())topic="General";try{JSONArray a=new JSONArray(sp.getString("sessions","[]"));JSONObject o=new JSONObject();o.put("date",new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()));o.put("time",new SimpleDateFormat("HH:mm",Locale.US).format(new Date()));o.put("skill",selectedSkill);o.put("topic",topic);o.put("seconds",elapsed);a.put(o);sp.edit().putString("sessions",a.toString()).apply();}catch(Exception e){}elapsed=0;startBtn.setText("Start");finishBtn.setEnabled(false);finishBtn.setAlpha(.5f);skillSpinner.setEnabled(true);topicInput.setEnabled(true);current.setText(selectedSkill+" • saved ✓");renderTimer();updateStreak();refresh();}
    void updateStreak(){sp.edit().putInt("streak",Math.min(999,sp.getInt("streak",0)+1)).apply();}
    void renderSkills(){skillsBox.removeAllViews();long today=todaySeconds();for(String s:skills){long skillSec=skillSeconds(s);double goal=getGoal(s)*3600;float pct=(float)Math.min(1,skillSec/goal);LinearLayout c=card();c.setPadding(16,12,16,12);LinearLayout top=new LinearLayout(this);TextView n=tv(s,16,TEXT);n.setTypeface(null,1);top.addView(n,new LinearLayout.LayoutParams(0,-2,1));top.addView(tv(Math.round(pct*100)+"%",14,GREEN));c.addView(top);ProgressBar pb=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);pb.setMax(100);pb.setProgress((int)(pct*100));pb.getProgressDrawable().setColorFilter(GREEN,android.graphics.PorterDuff.Mode.SRC_IN);c.addView(pb,new LinearLayout.LayoutParams(-1,12));c.addView(tv(formatShort(skillSec)+" / "+String.format(Locale.US,"%.1fh",getGoal(s)),12,MUTED));skillsBox.addView(c);}}
    long skillSeconds(String skill){long t=0;try{JSONArray a=new JSONArray(sp.getString("sessions","[]"));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);if(skill.equals(o.optString("skill"))&&new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()).equals(o.optString("date")))t+=o.optLong("seconds");}}catch(Exception e){}return t;}
    String formatShort(long s){if(s<60)return s+"s";if(s<3600)return (s/60)+"m";return String.format(Locale.US,"%.1fh",s/3600.0);}
    void renderSessions(){sessionsBox.removeAllViews();try{JSONArray a=new JSONArray(sp.getString("sessions","[]"));int count=0;for(int i=a.length()-1;i>=0&&count<8;i--){JSONObject o=a.getJSONObject(i);LinearLayout c=card();TextView x=tv(o.optString("skill")+"  •  "+o.optString("topic"),15,TEXT);x.setTypeface(null,1);c.addView(x);c.addView(tv(o.optString("date")+" "+o.optString("time")+"  •  "+formatShort(o.optLong("seconds")),12,MUTED));sessionsBox.addView(c);count++;}}catch(Exception e){}}
    void addSkill(){final EditText input=new EditText(this);input.setHint("Skill name");input.setSingleLine(true);new AlertDialog.Builder(this).setTitle("Add skill").setView(input).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{String s=input.getText().toString().trim();if(!s.isEmpty()&&!skills.contains(s)){skills.add(s);saveSkills();ArrayAdapter<String> ad=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,skills);skillSpinner.setAdapter(ad);refresh();}}).show();}
    @Override protected void onDestroy(){handler.removeCallbacks(tick);super.onDestroy();}
}
